<!--
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
-->
<div class="statistics" style="padding: 10px">
    <canvas id="chart_field_<?= $block->getField()->getId() ?>"  height="50px"></canvas>
    <script type="text/x-magento-init">
    {
        "#chart_field_<?= $block->getField()->getId() ?>": {
            "Alekseon_CustomFormsStatistics/js/chart": {
                "chartData": <?= /* @noEscape */ json_encode($block->getChartData()) ?>,
                "type": "<?= $block->getType() ?>"
            }
        }
    }
    </script>
</div>
