<!--
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
-->
<section>
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml($this->getField()->getDefaultFrontendLabel()) ?></span>
    </div>
    <div class="admin__page-section-content dashboard-container">
        <div class="col-m-3">
            <?= $block->getChartHtml(); ?>
        </div>
        <div class="col-m-9">
            <?= $block->getGridHtml(); ?>
        </div>
    </div>
</section>
